#!/usr/bin/env php
<?php
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

require_once(__DIR__.'/cli/bootstrap.php');

/**
 * CLI Codeigniter Crafstman 
 * Name changed to Ignite
 *
 * @author     David Sosa Valdes <https://github.com/davidsosavaldes>
 * @author     Oteng Kwame Appiah Nti <https://github.com/otengkwame>
 * @license    MIT License
 * @link       https://github.com/davidsosavaldes/Craftsman
 * @link       https://github.com/otengkwame/Ignite
 * @copyright  Copyright (c) 2016, David Sosa Valdes.
 * @copyright  Copyright (c) 2017, Oteng Kwame Appiah Nti.
 */
try 
{
	$dotenv = new Dotenv(getcwd(), '.env');
	$dotenv->load();
	$dotenv->required(['CI_BASEPATH','CI_APPPATH'])->notEmpty();

	define('IGNITEPATH', __DIR__.'/');

} 
catch (Exception $e) 
{
	exit(preg_replace('/\s+/', ' ', $e->getMessage()));
}

$generators = [
	new CLI\Commands\Generators\Controller,
	new CLI\Commands\Generators\Model,
	new CLI\Commands\Generators\Migration,
	new CLI\Commands\Generators\Seeder,
	new CLI\Commands\Generators\Interfaces
];

$migrations = [
	new CLI\Commands\Migrations\Info,
	new CLI\Commands\Migrations\Version,
	new CLI\Commands\Migrations\Latest,
	new CLI\Commands\Migrations\Rollback,
	new CLI\Commands\Migrations\Reset,
	new CLI\Commands\Migrations\Refresh
];

$general = [
	new CLI\Commands\Serve,
	new CLI\Commands\Console,
	new CLI\Commands\Notes,
	new CLI\Commands\Seeder,
	new \CLI\Commands\Key
];

// Set the commands
$commands = array_merge($generators, $migrations, $general);

$application = new Application('Ignite', '1.0');

// Add the default commands
foreach ($commands as $key => $command) {
	$application->add($command);
}

$application->run();
